services:
  redis:
    image: redis:7-alpine
    container_name: sns-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgresql:
    image: postgres:16-alpine
    container_name: sns-postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sns
      POSTGRES_USER: sns
      POSTGRES_PASSWORD: sns1234
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
